source 'https://rubygems.org'
gem "rack"
gem "thin"
gem "eventmachine", "0.12.10"
gem "json"
gem "mongoid"
gem "bson_ext"
gem "sinatra-contrib"
gem "koala"
gem "twitter"
gem "oauth"
gem "sinatra", :require => "sinatra/base"
