source 'https://rubygems.org'
gem "rack"
gem "thin"
gem "eventmachine",  "1.0.0.beta.4.1"
gem "json"
gem "mongoid"
gem "bson_ext"
gem "sinatra-contrib"
gem "koala"
gem "sinatra", :require => "sinatra/base"
